### PR TITLE
save txt2vid options as txt

### PR DESCRIPTION
**Pull request by dvschultz**
I’ve seen a number of users request saving each video output’s arguments for reuse (especially seed values, which help in the vid2vid step). These updates will create an `args.txt` file in each output folder so users can batch output videos and still retain necessary arguments for later use.

### CODE REVIEW

**Comment by TimurY86** [comment]
Awesome! Hope this get's added soon! :)

**Comment by bfasenfest** [comment]
Was just talking to someone in the discord about this. Great job!

**Comment by pmonck** [comment]
Are there any plans to merge this into kabachuha:main ?

**Comment by kabachuha** [comment]
Yes, soon 🙃

**Review by kabachuha — APPROVED** [review]

**Pull request merged**
